packages:
  - packages/*
  - '!package-template'
  - '!packages/vue-place-selector'
  - '!packages/otp-input'
  - '!packages/vue-trix'
  - '!packages/vue-forms'
  - '!packages/vue-dataviewer'
  - '!packages/paystack-inline'

onlyBuiltDependencies:
  - vue-demi
