packages:
  - packages/*
  # - runner
  - '!runner'
  - '!package-template'
  # - '!packages/vue-place-selector'
  - '!packages/otp-input'
  - '!packages/vue-auth'
  - '!packages/vue-trix'
  - '!packages/vue-forms'
  - '!packages/vue-dataviewer'
  - '!packages/paystack-inline'
