packages:
  - packages/*
  # - runner
  # - '!package-template'
  # - '!packages/vue-place-selector'
  # - '!packages/otp-input'
  # - '!packages/vue-trix'
  # - '!packages/vue-auth'
  - '!packages/vue-forms'
  - '!packages/vue-dataviewer'
  # - '!packages/paystack-inline'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - vue-demi
