name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - 'synchronize'
      - 'opened'
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          corepack enable
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn lint` command
