name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - 'synchronize'
      - 'opened'
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Latest
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v4
      - name: Restore Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependencies-cache-${{ hashFiles('**/package.json') }}
  lint:
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v4
      - name: Restore Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependencies-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run lint
