name: Publish Latest to NPM via Yarn

on:
  workflow_call:
    secrets:
      TONEFLIX_RELEASE_TOKEN:
        required: true
      NPM_TOKEN:
        required: true
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy-npm-latest:
    if: github.ref == 'refs/heads/main'
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TONEFLIX_RELEASE_TOKEN }}
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          always-auth: true
          scope: '@toneflix'
      - name: Create NPMRC
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.TONEFLIX_RELEASE_TOKEN }}" >> ~/.npmrc
          echo "@toneflix:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo 'registry "https://registry.yarnpkg.com"' >> ~/.yarnrc
      - run: |
          corepack enable
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command
      - name: Version & Publish
        env:
          GH_TOKEN: ${{ secrets.TONEFLIX_RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "Github Workflow (on behalf of ${{ github.actor }})"
          git config user.email "users.noreply.github.com"
          yarn npm whoami
          yarn run ci:publish:latest
